### ISSUE TITLE
does `withdraw`  succeed?

### ISSUE THREAD

**Issue by spartucus** [xJonathanLEI/acctexchange#2]
I'm writing the same contract, but i found it hard to make user to withdraw balance from contract using contract's action interface, it came out with error like:
```
transaction declares authority '{"actor":"user","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [{"actor":"contract","permission":"eosio.code"}], and provided keys []
```
Any ideas?

**Comment by xJonathanLEI** [comment]
You need to configure the contract's authority so that the `eosio.code` permission can fully satisfy its `active` permission. Put something like:

    $ cleos set account permission acctexchange active '{"threshold": 1,"keys": [{"key": "your_public_key","weight": 1}],"accounts": [{"permission":{"actor":"acctexchange","permission":"eosio.code"},"weight":1}]}' owner

**Comment by spartucus** [comment]
Thanks for reply. And how to implement `deposit`? I see there's a `exchange` contract in eos depo, and i can deploy the contract, but not see deposit abi interface.

So my question is how to do it?
for example:
```
// contract.cpp
// @ abi action
void deposit(name user, asset balance)
{
	require_auth(user);
	
	// save user to table
	action(
		permission_level( from, N(active) ), N(eosio.token), N(transfer), std::make_tuple{user, _self, balance, std::string("")}
	).send();
}
```

So I'm wondering if i could using following command to deposit user?
```
cleos push action contract deposit '["user", "1.0000 SYS"]' -p user
```

I have tried this, it says error log like:
```
transaction declares authority '{"actor":"user","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [{"actor":"contract","permission":"eosio.code"}], and provided keys []
```

Thanks for your time.
